### PR TITLE
Lesson 2

### PR DESCRIPTION
**Pull request by olennikovandrey**

### CODE REVIEW

**Review by Dronom — CHANGES_REQUESTED** [review]
You should have only 1 src folder with components,assets and so on. it is not obvious that assets and guestLovesHotels component are stored in th-webpack folder

**Comment by Dronom** [comment]
you need to have only 1 package.json which located at the top of project

**Comment by Dronom** [comment]
also I was not able to run the project from TH-webpack subfolder
image

**Comment by olennikovandrey** [comment]
> You should have only 1 src folder with components,assets and so on. it is not obvious that assets and guestLovesHotels component are stored in th-webpack folder

i think the "trip-house" folder is not needed. Only TH-webpack.

**Pull request merged**
